
import { Font, Category } from './types';

export const MOCK_FONTS: Font[] = [
  {
    family: 'Noto Sans SC',
    chineseName: '思源黑体',
    category: Category.SANS_SERIF,
    variants: ['100', '300', '400', '500', '700', '900'],
    subsets: ['chinese-simplified', 'latin'],
    version: '2.004',
    lastModified: '2023-08-15',
    files: {},
    description: 'Adobe 与 Google 历时数年联合打造的顶级开源字体。',
    designer: 'Adobe & Google',
    license: 'SIL OFL 1.1',
    copyright: '© Adobe Systems Incorporated.',
    source: '思源系列',
    features: '7 种字重，中日韩全覆盖，极简百搭，高清晰度。',
    scenarios: '网页设计、品牌 UI、长文本正文排版。'
  },
  {
    family: 'Noto Serif SC',
    chineseName: '思源宋体',
    category: Category.SERIF,
    variants: ['200', '300', '400', '500', '600', '700', '900'],
    subsets: ['chinese-simplified', 'latin'],
    version: '2.001',
    lastModified: '2023-01-20',
    files: {},
    description: '思源宋体在保持排版一致性的同时，展现了中文书法的神韵。',
    designer: 'Adobe & Google',
    license: 'SIL OFL 1.1',
    copyright: '© Adobe Systems Incorporated.',
    source: '思源系列',
    features: '传统韵味，撇捺精致，文学性极强，印刷效果卓越。',
    scenarios: '书籍装帧、文艺海报、高端品牌标题、文学排版。'
  },
  {
    family: 'Jiangxi ZhuoKai',
    chineseName: '江西拙楷',
    category: Category.HANDWRITING,
    variants: ['400'],
    subsets: ['chinese-simplified'],
    version: '1.0',
    lastModified: '2023-05-12',
    files: {},
    description: '带有半手工雕刻质感的楷书，散发出浓郁的人文气息。',
    designer: '黄煜臣',
    license: '设计师授权免费商用',
    copyright: '© 黄煜臣.',
    source: '人文书法系列',
    features: '半手工质感，笔画拙朴自然，文艺范十足。',
    scenarios: '文创产品、传统文化设计、艺术插画配文。'
  },
  {
    family: 'HongLei XingShu',
    chineseName: '鸿雷行书简体',
    category: Category.HANDWRITING,
    variants: ['400'],
    subsets: ['chinese-simplified'],
    version: '2.0',
    lastModified: '2024-03-20',
    files: {},
    description: '潇洒俊逸的行书字体，兼具传统书法美感与现代排版易读性。',
    designer: '鸿雷',
    license: '官方授权免费商用',
    copyright: '© 鸿雷.',
    source: '人文书法系列',
    features: '潇洒流畅，连笔自然，极具节奏感与书写神韵。',
    scenarios: '标题设计、书籍排版、古风游戏界面。'
  },
  {
    family: 'YanShi XiaXingKai',
    chineseName: '演示夏行楷',
    category: Category.HANDWRITING,
    variants: ['400'],
    subsets: ['chinese-simplified'],
    version: '1.0',
    lastModified: '2023-11-01',
    files: {},
    description: '为演示文稿而优化的行楷，平衡了规范性与手写感。',
    designer: '演示帮',
    license: '作者授权免费商用',
    copyright: '© 演示帮.',
    source: '人文书法系列',
    features: '规范与书写感兼具，结构紧凑，识别度高。',
    scenarios: '幻灯片演示、学术报告标题、简约手账设计。'
  },
  {
    family: 'MuYao SoftPen',
    chineseName: '沐瑶软笔手写体',
    category: Category.HANDWRITING,
    variants: ['400'],
    subsets: ['chinese-simplified'],
    version: '1.0',
    lastModified: '2022-09-15',
    files: {},
    description: '温暖治愈的软笔手写，适合传达亲切、自然的情绪。',
    designer: '春颜秋色',
    license: '作者授权免费商用',
    copyright: '© 春颜秋色.',
    source: '人文书法系列',
    features: '柔和自然，带有真实的手写温度与墨迹质感。',
    scenarios: '贺卡、温馨邀请函、笔记记录、生活日志。'
  },
  {
    family: 'MaoKen FengYaSong',
    chineseName: '猫啃网风雅宋',
    category: Category.SERIF,
    variants: ['400'],
    subsets: ['chinese-simplified'],
    version: '1.5',
    lastModified: '2024-04-10',
    files: {},
    description: '改良自传统宋体，融入了独特的连笔设计，极具装饰性。',
    designer: '猫啃网',
    license: '作者授权免费商用',
    copyright: '© 猫啃网.',
    source: '人文书法系列',
    features: '改良传统宋体，优雅的连笔设计，古典与现代感并存。',
    scenarios: '中国风海报、高端礼品包装、特色标题。'
  },
  {
    family: 'BiaoXiaoZhi WuJieHei',
    chineseName: '标小智无界黑',
    category: Category.DISPLAY,
    variants: ['400', '700'],
    subsets: ['chinese-simplified'],
    version: '1.0',
    lastModified: '2024-03-01',
    files: {},
    description: '一款专为品牌标题设计的扁平化黑体。',
    designer: '标小智团队',
    license: 'SIL OFL',
    copyright: '© BiaoXiaoZhi.',
    source: '创意设计系列',
    features: '扁平粗厚，视觉冲击力极强，去装饰化的工业美感。',
    scenarios: 'LOGO 设计、产品包装、大幅广告标题。'
  },
  {
    family: 'Aa HouDiHei',
    chineseName: 'Aa 厚底黑',
    category: Category.DISPLAY,
    variants: ['400'],
    subsets: ['chinese-simplified'],
    version: '1.0',
    lastModified: '2023-11-15',
    files: {},
    description: '粗犷与弧线完美结合的醒目字体。',
    designer: 'Aa 字库',
    license: '官方授权',
    copyright: '© AaFont.',
    source: '创意设计系列',
    features: '独特的厚重感，笔画转折处带有些许弧度，稳重且不失灵动。',
    scenarios: '艺术展览设计、网页大标题、时尚杂志封面。'
  },
  {
    family: 'PangMenZhengDao Title',
    chineseName: '庞门正道标题体',
    category: Category.DISPLAY,
    variants: ['400'],
    subsets: ['chinese-simplified'],
    version: '3.0',
    lastModified: '2024-02-20',
    files: {},
    description: '庞门正道系列中最受设计师欢迎的标题字体之一。',
    designer: '阿门 & 字体设计师',
    license: '设计师授权免费商用',
    copyright: '© PangMenZhengDao.',
    source: '庞门正道',
    features: '倾斜动感，笔画有力，吸睛效果显著，自带英雄气质。',
    scenarios: '电商促销大促、运动健身品牌、平面广告标题。'
  },
  {
    family: 'OPPO Sans',
    chineseName: 'OPPO Sans',
    category: Category.SANS_SERIF,
    variants: ['300', '400', '500', '700'],
    subsets: ['chinese-simplified', 'latin'],
    version: '3.0',
    lastModified: '2024-01-10',
    files: {},
    description: 'OPPO 品牌字体，旨在打造科技与人文交融的视觉体验。',
    designer: '汉仪字库',
    license: 'OPPO 免费商用授权',
    copyright: '© OPPO.',
    source: 'OPPO',
    features: '极简科技风，去装饰化设计，线条流畅舒展。',
    scenarios: '移动端 APP 界面、现代科技感文章、品牌 UI。'
  },
  {
    family: 'HarmonyOS Sans',
    chineseName: '鸿蒙正体',
    category: Category.SANS_SERIF,
    variants: ['100', '300', '400', '500', '700', '900'],
    subsets: ['chinese-simplified', 'latin'],
    version: '1.0',
    lastModified: '2023-12-05',
    files: {},
    description: '华为自研的面向全场景多终端的字体。',
    designer: '华为 & 汉仪',
    license: 'HarmonyOS 免费商用授权',
    copyright: '© Huawei.',
    source: '华为 (HarmonyOS)',
    features: '支持无级字重调节，动态渲染优化，极致的多终端适配性。',
    scenarios: '华为生态应用设计、物联网设备界面、系统底层字体。'
  },
  {
    family: 'Alibaba PuHuiTi 3.0',
    chineseName: '阿里巴巴普惠体',
    category: Category.SANS_SERIF,
    variants: ['300', '400', '500', '700', '900'],
    subsets: ['chinese-simplified', 'latin'],
    version: '3.0',
    lastModified: '2024-05-10',
    files: {},
    description: '阿里巴巴为全球商家打造的免费商用字体。',
    designer: '阿里巴巴 & 汉仪字库',
    license: '阿里巴巴免费商用授权',
    copyright: '© Alibaba Group.',
    source: '阿里巴巴',
    features: '覆盖 175+ 语种，包含可变字体技术，形态中正圆润。',
    scenarios: '电商详情页、企业宣传手册、全平台 UI 界面。'
  },
  {
    family: 'Roboto',
    category: Category.SANS_SERIF,
    variants: ['400', '700'],
    subsets: ['latin'],
    version: '3.0',
    lastModified: '2022-05-12',
    files: {},
    description: 'Android 系统的标准系统字体。',
    designer: 'Christian Robertson',
    license: 'Apache 2.0',
    copyright: 'Google Inc.',
    source: 'Google Fonts',
    features: '机械化骨架，几何感强，高度易读。',
    scenarios: '移动端系统界面、技术文档、现代简约网页。'
  }
];
